## Dragon Real Estate - Price Predictor

In [1]:
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
housing=pd.read_csv("Datasets/HousingData.csv")

In [3]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [5]:
housing['CHAS'].value_counts()

0    471
1     35
Name: CHAS, dtype: int64

In [6]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [7]:
%matplotlib inline

In [8]:
# #for plotting histogram
# import matplotlib.pyplot as plt
# housing.hist(bins=50, figsize=(20,15))

## Train-Test Splitting

In [9]:
'''import numpy as np
def split_tt(data,test_ratio):
    np.random.seed(42)
    shuffled=np.random.permutation(len(data))
    print(shuffled)
    test_set_size=int(len(data) * test_ratio)
    test_indices= shuffled[:test_set_size]
    train_indices= shuffled[test_set_size:]
    return data.iloc[train_indices],data.iloc[test_indices]'''

'import numpy as np\ndef split_tt(data,test_ratio):\n    np.random.seed(42)\n    shuffled=np.random.permutation(len(data))\n    print(shuffled)\n    test_set_size=int(len(data) * test_ratio)\n    test_indices= shuffled[:test_set_size]\n    train_indices= shuffled[test_set_size:]\n    return data.iloc[train_indices],data.iloc[test_indices]'

In [10]:
#train_set,test_set= split_tt(housing,0.2)
#print(f"Rows in train set: {len(train_set)}\nRows in test set:{len(test_set)}\n")

In [11]:
from sklearn.model_selection import train_test_split
train_set,test_set = train_test_split(housing,test_size=0.2, random_state=42)
print(f"Rows in train set: {len(train_set)}\nRows in test set:{len(test_set)}\n")

Rows in train set: 404
Rows in test set:102



In [12]:
# lets consider if CHAS is an important attribute and if during
#split all record with CHAS value =1 goes in to test set
#then our model will never get trained about CHAS=1 
#it will lead to worng presiction 


In [13]:
# So in order to properly split this dataset we need 
#to use Stratified Shuffle Split

from sklearn.model_selection import StratifiedShuffleSplit
split=StratifiedShuffleSplit(n_splits=1,test_size=0.2, random_state=42)
for train_index, test_index in split.split(housing,housing['CHAS']):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]

In [14]:
strat_train_set['CHAS'].value_counts()

0    376
1     28
Name: CHAS, dtype: int64

In [15]:
strat_test_set['CHAS'].value_counts() 

0    95
1     7
Name: CHAS, dtype: int64

In [16]:
housing= strat_train_set.copy()

## Looking for Correlations

In [17]:
corr_matrix=housing.corr()

In [18]:
corr_matrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.679894
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [19]:
# from pandas.plotting import scatter_matrix

# attributes=["MEDV","RM","ZN","LSTAT"]
# scatter_matrix(housing[attributes],figsize=(12,8))

In [20]:
#housing.plot(kind="scatter",x="RM",y="MEDV", alpha=0.8)


## Trying  Attribute combinations

In [21]:
housing["TAXRM"]=housing["TAX"]/housing["RM"]
housing.head()


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
254  0.04819  80.0   3.64     0  0.392  6.108  32.0  9.2203    1  315   
348  0.01501  80.0   2.01     0  0.435  6.635  29.7  8.3440    4  280   
476  4.87141   0.0  18.10     0  0.614  6.484  93.6  2.3053   24  666   
321  0.18159   0.0   7.38     0  0.493  6.376  54.3  4.5404    5  287   
326  0.30347   0.0   7.38     0  0.493  6.312  28.9  5.4159    5  287   

     PTRATIO       B  LSTAT  MEDV       TAXRM  
254     16.4  392.89   6.57  21.9   51.571709  
348     17.0  390.94   5.99  24.5   42.200452  
476     20.2  396.21  18.68  16.7  102.714374  
321     19.6  396.90   6.87  23.1   45.012547  
326     19.6  396.90   6.15  23.0   45.468948

In [22]:
corr_matrix=housing.corr()
corr_matrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.679894
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
TAXRM     -0.525160
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [23]:
#housing.plot(kind="scatter",x="TAXRM",y="MEDV", alpha=0.8)

In [24]:
housing_x= strat_train_set[["LSTAT","RM","DIS","CRIM","NOX"]]
housing_labels = strat_train_set["MEDV"].copy()

## Handling missing values


In [25]:
#1. removing the datapoint
#2. removing the attribute 
#3. replacing with mean or median of column


In [26]:
#for this preprocessing sklearn have "Imputer " module
from sklearn.impute import SimpleImputer

imputer=SimpleImputer(strategy='median')
imputer.fit(housing)


SimpleImputer(strategy='median')

In [27]:
imputer.statistics_

array([2.86735000e-01, 0.00000000e+00, 9.90000000e+00, 0.00000000e+00,
       5.38000000e-01, 6.21000000e+00, 7.82000000e+01, 3.12220000e+00,
       5.00000000e+00, 3.37000000e+02, 1.90000000e+01, 3.90955000e+02,
       1.15700000e+01, 2.11500000e+01, 5.39474541e+01])

In [28]:
X= imputer.transform(housing)

In [29]:
housing_tr = pd.DataFrame(X,columns=housing.columns)

In [30]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.279908   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.712983   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.210000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630250   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV       TAXRM  
count  404.000000  404.000000  404.000000  
mean    12.791609   22.509406   67.480852  
std      7.235740    9.385531   31.457774  
min      1.730000    5.000000   24.645639  
25%      6.847500   16.600000   44.801475  
50%     11.570000   21.150000   53.947454  
75%     17.102500   25.000000   98.317507  
max     36.980000   50.000000  187.026116

## Scikit learn Design

## Feature Scaling

Two types of Feature scaling primarily
1. Min-max scaling(Normalization)
    (value-min)/(max-min)
    sklearn provides a class called MinMaxScaler for this
    
2. Standardization
    (value - mean)/std
    sklearn provides a class StandardScaler for this 
    

## Creating a Pipeline

In [31]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline = Pipeline([
    ('imputer ', SimpleImputer(strategy='median')),
    # Can add as many as we want
    ('std_scaler', StandardScaler()),
    
])

In [32]:
housing_num_tr = my_pipeline.fit_transform(housing_x)

In [33]:
housing_num_tr.shape

(404, 5)

## Selecting a desired model for Dragon Real Estate

In [34]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
#model=DecisionTreeRegressor()
#model = LinearRegression()
model= RandomForestRegressor()
model.fit(housing_num_tr, housing_labels)

RandomForestRegressor()

In [35]:
some_data=housing_x.iloc[:5]
some_labels = housing_labels.iloc[:5]

prepared_data = my_pipeline.transform(some_data)

In [36]:
model.predict(prepared_data)

array([22.363, 25.244, 16.263, 23.4  , 23.599])

In [37]:
list(some_labels)

[21.9, 24.5, 16.7, 23.1, 23.0]

## Evaluating Model


In [38]:
from sklearn.metrics import mean_squared_error
import numpy as np
housing_pred = model.predict(housing_num_tr)
mse = mean_squared_error(housing_labels, housing_pred)
rmse = np.sqrt(mse)
print(rmse)

1.2718198565538879


Overfitting happened

## Using better evaluation technique - Cross Validation

In [39]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(model, housing_num_tr, housing_labels, scoring='neg_mean_squared_error', cv=10)
#cv= 10 folds

rmse_scores = np.sqrt(-scores)

In [40]:
print(rmse_scores)

[3.20870755 3.02996966 5.07090908 2.88294586 3.5627583  3.09140306
 4.57419442 3.40779074 3.36608071 3.37106262]


In [41]:
def print_scores(scores):
    print("Scores: ", scores)
    print("Mean: ", scores.mean())
    print("Standard deviation: ", scores.std())

In [42]:
print_scores(rmse_scores)

Scores:  [3.20870755 3.02996966 5.07090908 2.88294586 3.5627583  3.09140306
 4.57419442 3.40779074 3.36608071 3.37106262]
Mean:  3.55658219992844
Standard deviation:  0.67008364978796


## Saving the model to file


In [43]:
from joblib import dump,load
dump(model,"Dragon.joblib")

['Dragon.joblib']

## Testing the model


In [44]:
X_test = strat_test_set[["LSTAT","RM","DIS","CRIM","NOX"]]
Y_test = strat_test_set["MEDV"].copy()
X_test_Prep = my_pipeline.transform(X_test)
final_pred = model.predict(X_test_Prep)
final_mse = mean_squared_error(Y_test, final_pred)
final_rmse= np.sqrt(final_mse)


In [45]:
final_rmse

3.10327745942835

In [46]:
print(prepared_data[0])

[-0.86091034 -0.24141041  2.61111401 -0.43942006 -1.42262747]


## Using the model

In [49]:
from joblib import dump,load
import numpy as np
model = load("Dragon.joblib")
inputt = np.array([[-0.86091034,-0.24141041 , 2.61111401 ,-0.43942006, -1.42262747]])
model.predict(inputt)

array([22.363])

In [ ]:
plt.figure(figsize=(10,9))
feat_importances = pd.Series(model.feature_importances_, index = housing_x.columns)
feat_importances.nlargest(9).plot(kind='barh');
